from PyPDF2 import PdfMerger
import os

# Path to your downloaded PDFs
folder_path = r"https://1drv.ms/f/c/2ef3d1d790773116/EjHrL_mm1ZBNpZaqTMR_ceoBmVZSComo5LQiyxUFo_TVDw"
merger = PdfMerger()

for file in sorted(os.listdir(folder_path)):
    if file.endswith(".pdf"):
        merger.append(os.path.join(folder_path, file))

merger.write("merged.pdf")
merger.close()
print("✅ Merged PDF created successfully!")

